services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444" # Grid UI and Hub endpoint
      - "4442:4442" # Event bus (publish)
      - "4443:4443" # Event bus (subscribe)
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:4.21.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5900:5900" # VNC for Chrome debug
    shm_size: "2gb"
    networks:
      - grid

  firefox:
    image: selenium/node-firefox:4.21.0
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5901:5900" # VNC for Firefox debug
    shm_size: "2gb"
    networks:
      - grid

  edge:
    image: selenium/node-edge:4.21.0
    container_name: edge-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5902:5900" # VNC for Edge debug
    shm_size: "2gb"
    networks:
      - grid

  automation:
    build: .
    container_name: webautomation-framework
    depends_on:
      - selenium-hub
      - chrome
      - firefox
      - edge
    environment:
      # Inside Docker network use selenium-hub, not localhost
      - HUB_URL=http://selenium-hub:4444/
    command: >
      mvn clean test -P grid
    networks:
      - grid

networks:
  grid:
    driver: bridge
